ss-1

diff --git a/.github/workflows/ci-build.yml b/.github/workflows/ci-build.yml
--- a/.github/workflows/ci-build.yml
+++ b/.github/workflows/ci-build.yml
@@ -15,9 +15,22 @@ jobs:
       uses: actions/checkout@v3
     
     - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v3
+      with:
+        python-version: ${{ matrix.python-version }}
+        
+    - name: Install dependencies
       run: |
-        echo "done"
+        python -m pip install --upgrade pip
+        pip install -r requirements.txt
+        pip install pylint
+        
+    - name: Analysing the code with pylint
+      run: |
+        # Need to add true at the end as pylint will fail right now due to static code analysis findings
+        pylint $(git ls-files '*.py' | grep -v "dummy") || true
 
+        
   run-tests:
     name: Run Tests
     runs-on: ubuntu-latest
@@ -31,6 +44,7 @@ jobs:
         echo "Sleeping for 3"
         sleep 3
   
+
   docker-build:
     name: Docker Build
     runs-on: ubuntu-latest
@@ -43,7 +57,25 @@ jobs:
         uses: actions/checkout@v3
       
       - name: Set up QEMU
-        run: |
-          echo "done 2"
-
-          
+        uses: docker/setup-qemu-action@v3
+      
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+        with:
+          buildkitd-flags: --debug
+      
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: poonamsabharwal
+          password: dckr_pat_J61TsbBzpwqA4zOGTvtuiuvRprg
+      
+      - name: Build and push
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          file: ./Dockerfile
+          push: true
+          platforms: linux/amd64,linux/arm64
+          tags: poonamsabharwal/citadel-idp-frontend:latest
+    
